steps:
  # Step 1: Create .env file from secret
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$$SECRET" > .env && echo "Environment variables created successfully"
    secretEnv: ["SECRET"]

  # Step 2: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/${_PROJECT_ID}/backend/api:latest"
      - "--build-arg"
      - "ENV_FILE=.env"
      - "-f"
      - "Dockerfile"
      - "."

  # Step 3: Push the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${_PROJECT_ID}/backend/api:latest"

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "expense-bot-api"
      - "--image=us-central1-docker.pkg.dev/${_PROJECT_ID}/backend/api:latest"
      - "--platform=managed"
      - "--region=${_REGION}"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=4"
      - "--allow-unauthenticated"

availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/expense-bot-production-secrets/versions/latest
      env: "SECRET"

substitutions:
  _REGION: us-central1
  _PROJECT_ID: expense-bot-441618
