steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  env:
    - "DOCKER_BUILDKIT=1"
  args:
    - "build"
    - "--no-cache"
    - "--build-arg"
    - "HF_TOKEN=${_HF_TOKEN}"
    - "--secret"
    - "id=HF_TOKEN,env=HF_TOKEN"
    - "--tag"
    - "${_IMAGE}"
    - "."

images: ["${_IMAGE}"]

substitutions:  
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-gemma-2-2b-it-repo/vllm-gemma-2-2b-it'
  _HF_TOKEN: ""  # Will be provided during build submission

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_32"